[package]
name = "stoilib"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
ndarray = "0.16.1"
ndarray-stats = "0.6.0"
num = "0.4.3"
realfft = "3.5.0"
windowfunctions = "0.1.1"
