[package]
name = "stoi"
version = "0.1.0"
edition = "2024"

[lib]
name = "fast_stoi_python"
crate-type = ["cdylib"]

[dependencies]
numpy = "0.27.1"
pyo3 = "0.27.2"
fast-stoi = { path = "../fast-stoi" }
ndarray = { version = "0.17.1", features = ["rayon"] }
